ask2_4: ask2_4.o proc-common.o tree.o
	gcc ask2_4.o proc-common.o tree.o -o ask2_4


ask2-signals: ask2-signals.o proc-common.o tree.o
		gcc ask2-signals.o proc-common.o tree.o -o ask2_signals

ask2_4.o: ask2_4.c
	gcc -Wall -c ask2_4.c

ask2-signals.o: ask2-signals.c
	gcc -Wall -c ask2-signals.c

ask2_1b: ask2_1b.o proc-common.o tree.o
		gcc ask2_1b.o proc-common.o tree.o -o ask2_1b

ask2_1b.o: ask2_1b.c
	gcc -Wall -c ask2_1b.c

ask2_1a: ask2_1a.o proc-common.o tree.o
		gcc ask2_1a.o proc-common.o tree.o -o ask2_1a

ask2_1a.o: ask2_1a.c
	gcc -Wall -c ask2_1a.c

proc-common.o:proc-common.c
	gcc -Wall -c proc-common.c

tree.o: tree.c
	gcc -Wall -c tree.c

